### ISSUE TITLE
Cannot get this to work?

### ISSUE THREAD

**Issue by richd67** [QWxleA/Unfinished-business#1]
Not on marketplace so uploaded as unpacked, but cannot get it to work. Simple get the error of 'Cannot find any (tagged) tasks'. This is both with the testme and without in settings?

**Comment by QWxleA** [comment]
Thank you for the issue. Updated the README, hope it is clearer now. The code works, afaik, but the README was unclear. Please let me know if it is still unclear.

Also, should be in the marketplace any moment now 🎈. And is now installable from the marketplace. 🎉

**Comment by QWxleA** [comment]
Should work with better docs, if not, reopen
